-- ponytail: exact schema definitions from PRD Section 5
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE,
  full_name TEXT,
  last_vehicle_used TEXT DEFAULT 'motor',
  role TEXT DEFAULT 'user'  -- 'god' reserved for Fatih
);

CREATE TABLE saved_places (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  place_name TEXT NOT NULL,  -- e.g., 'Home', 'Kampus IPB', 'Cafe A'
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  vehicle_type TEXT NOT NULL,  -- 'motor', 'mobil', 'angkot', 'kereta', etc.

  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE,  -- NULL if running / timeout

  -- GPS coordinates (supports both saved places & instant capture)
  start_lat DOUBLE PRECISION NOT NULL,
  start_lng DOUBLE PRECISION NOT NULL,
  end_lat DOUBLE PRECISION,
  end_lng DOUBLE PRECISION,

  start_place_id BIGINT REFERENCES saved_places(id),
  end_place_id BIGINT REFERENCES saved_places(id),

  duration_minutes INTEGER,  -- Auto-calculated on checkout
  weather_condition TEXT,    -- Auto-fetched from Open-Meteo
  regional_event TEXT,       -- Auto-fetched from calendar API

  status TEXT DEFAULT 'running' 
    CHECK (status IN ('running', 'completed', 'timeout', 'manual_fix')),

  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
